spring:
  application:    name: MS-Gateway
    
server:  port: 8090
eureka:
  instance:
    intance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    #service-url.defaultZone: http://eureka-server:8761/eureka
    service-url.defaultZone: http://localhost:8761/eureka
    #service-url.defaultZone: http://192.168.99.100:8761/eureka
    
    
zuul:
  #ignoredHeaders: authorization
  routes:
    users:
      service-id: MS-Usuarios
      path: /api/users/**  
    security:
      service-id: MS-Oauth
      path: /api/security/**
      sensitiveHeaders: Cookie,Set-Cookie
    ida:
      service-id: MS-IDA
      path: /api/ida/**
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
 
   
           
MS-Usuarios:
  ribbon:
    ReadTimeout: 500000
MS-Oauth:
  ribbon:
    ReadTimeout: 500000
MS-IDA:
  ribbon:
    ReadTimeout: 500000
    
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    

    